[project]
name = "keepnote"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.0.2",
    "ruff>=0.15.1",
]



[tool.ruff]
target-version = "py313"  # Target your specific Python version

[tool.ruff.lint]
select = ["UP"]  # Enable pyupgrade rules
